//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeRegister
    {
        public int ID { get; set; }
        public string Emp_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Department { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Country { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public byte[] ProfilePic { get; set; }
    }
}
