//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ID { get; set; }
        public string PRODT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string PRODT_TYPE { get; set; }
        public string OWNER { get; set; }
        public string ASSIGNED_TO { get; set; }
    }
}
