//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegisterCustomer
    {
        public int ID { get; set; }
        public string SponserID { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public byte[] Photo { get; set; }
    }
}
